### ISSUE TITLE
Is it possible to validate based on specific values?

### ISSUE THREAD

**Issue by oscarcalderonc** [ggicci/httpin#111]
Hi, thanks for this awesome library. I was just wondering if it is possible to restrict input for fields based on a set of values, like:

```
type MyInput struct {
	SubId string `json:"subscriptionID"`
	Behavior    string `json:"endBehavior" possible_values=cancel,apply`
}
```

If it is already possible, I cannot find it in the documentation

**Comment by ggicci** [comment]
hi @oscarcalderonc , unfortunately httpin doesn't support this. I would suggest using some other packages that focus on solving problems in this area, i.e. struct fields validations, for example https://github.com/go-ozzo/ozzo-validation is a good choice.

Since it's a design decision made at the very first begining and even today I still belive this is not the problem httpin needs to solve. Hope this helps :)

I'm closing this ticket. But feel free to open it if needed.
