### ISSUE TITLE
Require doesn't work as expected when using mixed body input

### ISSUE THREAD

**Issue by AlessandroSechi** [ggicci/httpin#49]
Following [this](https://github.com/ggicci/httpin/issues/45#issuecomment-1240494027) example, the `required` tag doesn't work as expected.
```
type UpdateUserInput struct {
	Payload struct {
		Display string `json:"display" in:"required"`
	} `in:"body=json"`
}
```

If body is not passed in request, no error is thrown (while it should)

**Comment by ggicci** [comment]
Hi @AlessandroSechi, actually httpin won't traverse recursively into deeper levels of the input struct. Which means only the 1st level of the fields tagged with `in` directives will be executed. This is by design, in order to reduce complexity.

Example:

```go
type FooInput struct {
	Token  string `in:"header=Authorization"` // ok
	Color  string `in:"query=color"`          // ok
	Nested struct {
		Name string `in:"query=name"` // not ok
	}
}

// input
// POST "/foo?name=apple&color=red"
// Header: Authorization: my-secret-here
// output
// &main.FooInput{Token:"my-secret-here", Color:"red", Nested:struct { Name string "in:\"query=name\"" }{Name:""}}
```

Try it here: https://goplay.tools/snippet/SLZh8JXjMsL

For your snippet above, once httpin has run the `body` directive on the 1st level field `Payload`, it's done. The inner fields including `Display` of `Payload` won't get touched. This is why the `required` tag won't work.

IMO, httpin will and should focus on defining the process of data extracting and leave validation related stuff to other Go packages. Here `required` is really an exception. However, to some extent the `required` directive is an essential part of httpin as its function is really limited but frequently-used.


For your usecase, I'd like to suggest another package for struct validation: https://github.com/go-ozzo/ozzo-validation.

**Comment by ggicci** [comment]
The directives defined in a nested struct will be executed now, since [v0.12.0](../releases/tag/v0.12.0) (brought in via [ggicci/owl@v0.1.17](https://github.com/ggicci/owl/blob/v0.1.7/resolver_test.go#L533)). TODO: update docs.

**Comment by AlessandroSechi** [comment]
Awesome! Thanks

**Comment by ashl1** [comment]
@ggicci Thank you for you work.
But both with 0.12.0 and latest 0.14.2 the example in the first message of the thread doesn't work.
```json
{
  "field": "Payload",
  "source": "required",
  "key": "",
  "value": null,
  "error": "resolve field \"Payload (struct { Display string \\\"json:\\\\\\\"display\\\\\\\" in:\\\\\\\"required\\\\\\\"\\\" })\" failed: resolve field \"Payload.Display (string)\" failed: execute directive \"required\" with args [] failed: missing required field"
}
```

And in source code I don't see any tests of `required` with `json` body, only for `query` and `form`. Maybe I miss something?

**Comment by ggicci** [comment]
Hi @ashl1, the `required` directive always works with at least one another directive together, and it checks whether the field is set by a former directive or not, even the final value is a "zero" value. It doesn't run validations like ensuring the value not to be empty or zero. Another limitation is that, the `required` directive doesn't know if the the field tagged as required (`Display`) is set/populated by a directive that run by a parent field (`Payload`). That's why it threw an error.

I admit that the designed behaviour of directive `required` has brought a lot of confusion. I will reconsider it and make it more clear and easy to use.

**Comment by ggicci** [comment]
Let me explain the design purpose of `required` directive again here.

The `required` directive is used to make sure the key is present in the input data. It always works together with other directives, for example:

```go
type Payload struct {
	Name   string `in:"query=name;required"`      // ensure the key "name" is present in querystring
	Age    int    `in:"form=age;required"`        // ensure the key "age" is present in the submitted form
	Secret string `in:"header=x-secret;required"` // ensure the key "x-secret" is present in HTTP header
}
```

It's not designed to check the final value of the tagged field is empty/zero or not.

**Comment by ggicci** [comment]
A new directive [**nonzero**](https://ggicci.github.io/httpin/directives/nonzero) is introduced since [v0.15.0](../releases/v0.15.0).

**Comment by ggicci** [comment]
Difference between `required` and `nonzero` please read https://ggicci.github.io/httpin/directives/required
